### ISSUE TITLE
Show seed in the address line/generated page 

### ISSUE THREAD

**Issue by baba-beda** [thewinniewu/aeropress-dice#1]
That would be nice if it was possible to save recipes in the form of the generated link.

As an intermediate step the page can contain the seed and another ui element can show the recipe from this seed. (could be fun for showing "birthday" recipes)

Potentially afterwards you can add an integration for easy sharing of the links in the social media.

**Comment by thewinniewu** [comment]
Hey! SO SORRY for the delayed response, this is a side project for me so I haven't had a lot of time to get around to this until now >_< but wanted to let you know there is now a way to do this in the app! :D
